// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBLsNzZhLiltT3SPG1RSTYsqDRS81Twh6k',
    appId: '1:624383909624:web:b5aa61e0b24506889b250d',
    messagingSenderId: '624383909624',
    projectId: 'presence-ad54b',
    authDomain: 'presence-ad54b.firebaseapp.com',
    storageBucket: 'presence-ad54b.firebasestorage.app',
    measurementId: 'G-287JDR5RKH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBaiceGe8-kMV7IAhR3-IskzsDrDrAXCf0',
    appId: '1:624383909624:android:7b2e95bba5d55ceb9b250d',
    messagingSenderId: '624383909624',
    projectId: 'presence-ad54b',
    storageBucket: 'presence-ad54b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAYyK6RrYGXa2Hhj0Gj0MYnrD26GAI7o0g',
    appId: '1:624383909624:ios:0365d856c6e82a5f9b250d',
    messagingSenderId: '624383909624',
    projectId: 'presence-ad54b',
    storageBucket: 'presence-ad54b.firebasestorage.app',
    iosBundleId: 'com.dan.presence',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAYyK6RrYGXa2Hhj0Gj0MYnrD26GAI7o0g',
    appId: '1:624383909624:ios:0365d856c6e82a5f9b250d',
    messagingSenderId: '624383909624',
    projectId: 'presence-ad54b',
    storageBucket: 'presence-ad54b.firebasestorage.app',
    iosBundleId: 'com.dan.presence',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBLsNzZhLiltT3SPG1RSTYsqDRS81Twh6k',
    appId: '1:624383909624:web:4dccfd4a7ea54ace9b250d',
    messagingSenderId: '624383909624',
    projectId: 'presence-ad54b',
    authDomain: 'presence-ad54b.firebaseapp.com',
    storageBucket: 'presence-ad54b.firebasestorage.app',
    measurementId: 'G-6Y4N1FVWC6',
  );
}
